### PR TITLE
pass required argument

### LINKED ISSUE #94: Function block inside entwine definition does not take $ argument properly
Usage of entwine with a namespace [apparently demeans that we accept jQuery/$ as an argument][1].
But in [SessionManagerFieldEntwine.js#L20][2] we don't accept any arguments.

From what I can tell, just adding a `$` gets rid of the warning, so should be a simple fix.

[1]: https://github.com/hafriedlander/jquery.entwine/blob/master/src/jquery.entwine.js#L323
[2]: https://github.com/silverstripe/silverstripe-session-manager/blob/1/client/src/legacy/SessionManagerFieldEntwine.js#L20

### PR DESCRIPTION
**Pull request by lekoala**
Fixes https://github.com/silverstripe/silverstripe-session-manager/issues/94

the argument is required by entwine

### CODE REVIEW

**Review by michalkleiner — APPROVED** [review]

**Review by michalkleiner — CHANGES_REQUESTED** [review]
The Travis failure is related
Screen Shot 2021-11-30 at 10 48 43 AM

In all other `.js` files a block like that is always wrapped like so:
```
(function($) {
  $.entwine('ss', function($) {
   ...
  }); // ss namespace
}(jQuery));
```

**Comment by lekoala** [comment]
@michalkleiner mhh maybe we just name it to something else even if it not used

**Comment by michalkleiner** [comment]
@lekoala did you try wrapping it in the [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression)? No dice?

**Comment by lekoala** [comment]
@michalkleiner we can try :)

**Comment by emteknetnz** [comment]
Closed in favor of https://github.com/silverstripe/silverstripe-session-manager/pull/99

@lekoala I've put you down as a co-author in the commit message of the new PR

**Pull request closed without merging**
